# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - "Platform/GitHubActions"
      - "Status/Pending ðŸ”µ"
      - "Type/Dependency ðŸ“¦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "Etc/UTC"
    groups:
      development:
        patterns:
          - "@*/eslint-config-*"
          - "@*/eslint-config"
          - "@*/eslint-formatter-*"
          - "@*/eslint-formatter"
          - "@*/eslint-parser-*"
          - "@*/eslint-parser"
          - "@*/eslint-plugin-*"
          - "@*/eslint-plugin"
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint-config-*"
          - "eslint-formatter-*"
          - "eslint-parser-*"
          - "eslint-plugin-*"
          - "eslint"
          - "typescript"
    labels:
      - "Platform/NodeJS"
      - "Status/Pending ðŸ”µ"
      - "Type/Dependency ðŸ“¦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    versioning-strategy: "increase"
