# $<Schema>$ https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - "Status/Unread ðŸ”µ"
      - "Type/Dependency ðŸ“¦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "disabled"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - "Status/Unread ðŸ”µ"
      - "Type/Dependency ðŸ“¦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - "Status/Unread ðŸ”µ"
      - "Type/Dependency ðŸ“¦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "disabled"
    versioning-strategy: "auto"
