version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - "Platform/GitHub/Actions :octocat:"
      - "Status/Pending ðŸ”µ"
      - "Type/Dependency ðŸ“¦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - "Platform/NodeJS ðŸ”˜"
      - "Status/Pending ðŸ”µ"
      - "Type/Dependency ðŸ“¦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "disabled"
    versioning-strategy: "increase"
