name: "Announce New Release - Discord"
on:
  release:
    types:
      - "published"
jobs:
  announce-new-release-discord:
    name: "Announce New Release - Discord"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/send-discord-webhook-ghaction/use-nodejs@main"
        with:
          key: "${{secrets.DISCORD_WEBHOOK_HXHS_PROJECTNEWRELEASEANNOUNCER}}"
          payload: |
            embeds:
              - title: "Send Discord Webhook (GitHub Action)"
                description: |
                  > ${{github.event.repository.description}}

                  Version ${{github.event.release.name}} (${{github.event.release.tag_name}}) just released!
                color: "16,116,231"
                thumbnail:
                  url: "https://i.imgur.com/6qM8z4w.png"
                fields:
                  - name: "GitHub: ${{github.event.repository.full_name}}"
                    value: "${{github.event.repository.html_url}}"
                    inline: true
                  - name: "GitHub Repository Release & Changelog"
                    value: "${{github.event.release.html_url}}"
                    inline: true
                  - name: "GitHub Marketplace"
                    value: "https://github.com/marketplace/actions/send-discord-webhook"
                    inline: true
                  - name: "．"
                    value: "．"
                    inline: false
                  - name: "Author"
                    value: "${{github.event.release.author.login}}"
                    inline: true
                  - name: "Publish Time"
                    value: "${{github.event.release.published_at}}"
                    inline: true
          wait: "true"
