name: "Announce New Release - Discord"
on:
  release:
    types:
      - "published"
jobs:
  announce-new-release-discord:
    name: "Announce New Release - Discord"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/send-discord-webhook-ghaction@main"
        with:
          key: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_PROJECTNEWRELEASEANNOUNCER}}"
          payload: |
            content: |
              **__Send Discord Webhook (GitHub Action)__**

              Version ${{github.event.release.name}} (${{github.event.release.tag_name}}) is released and available on:

              - **GitHub Repository Release (& Changelog):** <${{github.event.release.html_url}}>
              - **GitHub Marketplace:** <https://github.com/marketplace/actions/send-discord-webhook>
            embeds:
              - description: |
                  **__Send Discord Webhook (GitHub Action)__**

                  ${{github.event.repository.description}}

                  - **GitHub:** ${{github.event.repository.html_url}}
                color: "16,116,231"
                thumbnail:
                  url: "https://i.imgur.com/knmLbFg.png"
          wait: "true"
