# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Code Analysis - GitHub Super Linter"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
  workflow_dispatch:
jobs:
  code-analysis-ghsl:
    name: "Code Analysis - GitHub Super Linter"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.4.0"
        with:
          fetch-depth: 0
      - name: "Analyze Repository"
        uses: "github/super-linter@v4.8.1"
        env:
          DISABLE_ERRORS: "true"
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          LINTER_RULES_PATH: ".github/linters"
          LOG_LEVEL: "VERBOSE"
          MULTI_STATUS: "true"
          OUTPUT_DETAILS: "detailed"
          VALIDATE_ALL_CODEBASE: "true"
