# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "New Release Announcer - IFTTT"
on:
  release:
    types:
      - "published"
jobs:
  new-release-announcer-ifttt:
    name: "New Release Announcer - IFTTT"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/trigger-ifttt-webhook-applet-ghaction@v4.0.0"
        with:
          eventname: "githubaction_twitter"
          key: "${{secrets.IFTTTWEBHOOK_HUGOALH_KEY}}"
          payload: |
            {
              "value1": "Send Discord Webhook (GitHub Action Edition) version ${{github.event.release.name}} (${{github.event.release.tag_name}}) is released and available on GitHub!\n${{github.event.release.html_url}}"
            }
