name: "New Release Announcer - IFTTT"
on:
  release:
    types:
      - "published"
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/GitHubAction.SendToIFTTT@v4.0.1"
        with:
          webhook_eventname: "githubaction_twitter"
          webhook_key: "${{secrets.IFTTTWEBHOOK_HUGOALH_KEY}}"
          variable_join: "."
          # variable_list_external:
          variable_prefix: "%"
          variable_suffix: "%"
          value1: "[GitHub Action] Send To Discord version %payload.release.name% (%payload.release.tag_name%) is released and available on GitHub!\n%payload.release.html_url%"
          # value2:
          # value3:
