# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Scan Virus"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
  workflow_dispatch:
    inputs:
      cache:
        description: "{boolean} Cache data."
        required: false
        default: "true"
      deep:
        description: "{boolean} Scan deeper."
        required: false
        default: "true"
jobs:
  parse-inputs:
    name: "(Parse Inputs)"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          [string]$Cache = '${{github.event.inputs.cache}}'
          [string]$Deep = '${{github.event.inputs.deep}}'
          if ($Cache.Length -eq 0) {
            $Cache = 'true'
          }
          if ($Deep.Length -eq 0) {
            $Deep = 'false'
          }
          Write-Host -Object "::set-output name=cache::$Cache"
          Write-Host -Object "::set-output name=deep::$Deep"
        id: "parser"
        shell: "pwsh"
    outputs:
      cache: "${{steps.parser.outputs.cache}}"
      deep: "${{steps.parser.outputs.deep}}"
  scan-virus:
    name: "Scan Virus"
    runs-on: "ubuntu-latest"
    needs:
      - "parse-inputs"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.2"
        with:
          fetch-depth: 0
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction@v0.5.0"
        with:
          cache: "${{needs.parse-inputs.outputs.cache}}"
          deep: "${{needs.parse-inputs.outputs.deep}}"
