# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Scan Virus"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
  workflow_dispatch:
    inputs:
      git_integrate:
        type: "choice"
        description: "{Boolean} Whether to integrate with Git to perform scan by every commits."
        required: false
        default: "False"
        options:
          - "False"
          - "True"
      git_limit:
        type: "string"
        description: "{UInt64} Limit on how many Git commits will scan."
        required: false
        default: "0"
      git_reverse:
        type: "choice"
        description: "{Boolean} Whether to reverse the scan order of the Git commits."
        required: false
        default: "False"
        options:
          - "False"
          - "True"
jobs:
  main:
    name: "Main"
    permissions:
      contents: "read"
    uses: "hugoalh/hugoalh/.github/workflows/call-scan-virus-0.yml@main"
    with:
      git_integrate: "${{github.event.inputs.git_integrate || 'False'}}"
      git_limit: "${{github.event.inputs.git_limit || '0'}}"
      git_reverse: "${{github.event.inputs.git_reverse || 'False'}}"
      ignores_post: |-
        Param($ElementPostMeta)
        Return (
          $ElementPostMeta.Path -imatch '^node_modules[\\/]'
        )
