# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Scan Virus"
on:
  pull_request:
    branches:
      - "**"
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      git_integrate:
        type: "choice"
        description: "{Boolean} Whether to integrate with Git to perform scan by every commits."
        required: false
        default: "False"
        options:
          - "False"
          - "True"
      git_limit:
        type: "string"
        description: "{UInt64} Limit on how many Git commits will scan."
        required: false
        default: "0"
      git_reverse:
        type: "choice"
        description: "{Boolean} Whether to reverse the scan order of the Git commits."
        required: false
        default: "False"
        options:
          - "False"
          - "True"
jobs:
  main:
    if: "${{!(github.event_name == 'pull_request' && github.event.pull_request.head.repo.id == github.event.pull_request.base.repo.id)}}"
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: "0"
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction/clamav@v0.20.1"
        with:
          git_integrate: "${{inputs.git_integrate || 'False'}}"
          git_limit: "${{inputs.git_limit || '0'}}"
          git_reverse: "${{inputs.git_reverse || 'False'}}"
          ignores_post: |-
            Param($ElementPostMeta)
            Return (
              $ElementPostMeta.Path -imatch '^node_modules[\\/]'
            )
  skip:
    if: "${{github.event_name == 'pull_request' && github.event.pull_request.head.repo.id == github.event.pull_request.base.repo.id}}"
    permissions: {}
    runs-on: "ubuntu-latest"
    steps:
      - run: |-
          sleep 1
